version: "3.9"
services:
  db:
    image: "postgres:12.9"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=test"
      - "POSTGRES_DB=db_remind"
    ports:
      - "5432:5432"